/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.example.demo.utilities;

import com.example.demo.list.LinkedList;

class SplitUtils {
  public static LinkedList split(String source) {
    var lastFind = 0;
    var currentFind = 0;
    var result = new LinkedList();

    while ((currentFind = source.indexOf(" ", lastFind)) != -1) {
      var token = source.substring(lastFind);
      if (currentFind != -1) {
        token = token.substring(0, currentFind - lastFind);
      }

      addIfValid(token, result);
      lastFind = currentFind + 1;
    }

    var token = source.substring(lastFind);
    addIfValid(token, result);

    return result;
  }

  private static void addIfValid(String token, LinkedList list) {
    if (isTokenValid(token)) {
      list.add(token);
    }
  }

  private static boolean isTokenValid(String token) {
    return !token.isEmpty();
  }
}
