/*
 * This file was generated by the Gradle 'init' task.
 */

plugins { id("com.example.demo.java-library-conventions") }

dependencies {
  implementation("org.springframework:spring-tx")
  implementation(project(":domain"))
  implementation(project(":infrastructure"))
}
