version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "07:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    reviewers:
      - ponko2
    commit-message:
      prefix: ci
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
      time: "07:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    reviewers:
      - ponko2
    commit-message:
      prefix: build
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "07:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    reviewers:
      - ponko2
    commit-message:
      prefix: build
    versioning-strategy: increase
    groups:
      babel:
        patterns:
          - "@babel/*"
          - babel-loader
      commitlint:
        patterns:
          - "@commitlint/*"
      jest:
        patterns:
          - babel-jest
          - jest
          - jest-environment-jsdom
      secretlint:
        patterns:
          - "@secretlint/*"
          - secretlint
      storybook:
        patterns:
          - "@storybook/*"
          - storybook
      types:
        patterns:
          - "@types/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      vite:
        patterns:
          - "@vitejs/plugin-react"
          - vite
