/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.example.demo.app;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

import org.junit.jupiter.api.Test;

class MessageUtilsTest {
  @Test
  void testGetMessage() {
    assertThat(MessageUtils.getMessage(), is("Hello      World!"));
  }
}
