[versions]
spring-boot = "2.7.0"

[libraries]
errorprone = "com.google.errorprone:error_prone_core:2.14.0"
gradle-dependency-management = "io.spring.gradle:dependency-management-plugin:1.0.11.RELEASE"
gradle-errorprone = "net.ltgt.gradle:gradle-errorprone-plugin:2.0.2"
gradle-spotless = "com.diffplug.spotless:spotless-plugin-gradle:6.3.0"
gradle-spring-boot = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot" }
nullaway = "com.uber.nullaway:nullaway:0.9.7"
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }

[plugins]
frontend = "org.siouan.frontend-jdk11:6.0.0"
