[versions]
immutables = "2.9.0"
spring-boot = "2.6.4"

[libraries]
gradle-dependency-management = "io.spring.gradle:dependency-management-plugin:1.0.11.RELEASE"
gradle-spring-boot = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot" }
hamcrest-optional = "com.github.npathai:hamcrest-optional:2.0.0"
immutables = { module = "org.immutables:value", version.ref = "immutables" }
immutables-annotations = { module = "org.immutables:value-annotations", version.ref = "immutables" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }

[plugins]
frontend = "org.siouan.frontend-jdk11:6.0.0"
