/*
 * This file was generated by the Gradle 'init' task.
 */

plugins { id("com.example.demo.java-application-conventions") }

dependencies {
  implementation("org.apache.commons:commons-text")
  implementation("org.springframework.boot:spring-boot-starter")
  implementation(project(":utilities"))
  developmentOnly("org.springframework.boot:spring-boot-devtools")
  runtimeOnly("mysql:mysql-connector-java")
  annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")
}
