version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick an version of Java: 11, 17.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 17-bullseye
        # Options
        INSTALL_MAVEN: "false"
        MAVEN_VERSION: ""
        INSTALL_GRADLE: "false"
        GRADLE_VERSION: ""
        NODE_VERSION: lts/*

    environment:
      # NOTE: MYSQL_DATABASE/USER/PASSWORD should match values in db container
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_HOSTNAME: db

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mysql:8.0-oracle
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      # NOTE: MYSQL_DATABASE/USER/PASSWORD should match values in app container
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql

    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MySQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  mysql-data:
