/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  // Apply the common convention plugin for shared build configuration between library and application projects.
  id("com.example.demo.java-common-conventions")

  id("org.springframework.boot")
}
