/*
 * This file was generated by the Gradle 'init' task.
 */

fun library(alias: String) = extensions.getByType<VersionCatalogsExtension>().named("libs").findLibrary(alias).get()

plugins {
  // Apply the java Plugin to add support for Java.
  java

  id("io.spring.dependency-management")
}

group = "com.example"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_17

configurations {
  compileOnly {
    extendsFrom(configurations.annotationProcessor.get())
  }
}

repositories {
  // Use Maven Central for resolving dependencies.
  mavenCentral()
}

dependencies {
  implementation(platform(library("spring-boot-dependencies")))
  annotationProcessor(library("immutables"))
  compileOnly(library("immutables-annotations"))
  testImplementation("org.springframework.boot:spring-boot-starter-test")
  testImplementation(library("hamcrest-optional"))
}

tasks.withType<Test>().configureEach {
  // Use JUnit Platform for unit tests.
  useJUnitPlatform()
}

sourceSets.main {
  java.srcDirs("src/main/java", "build/generated/sources/annotationProcessor/java/main")
}
