/*
 * This file was generated by the Gradle 'init' task.
 */

fun library(alias: String) = extensions.getByType<VersionCatalogsExtension>().named("libs").findLibrary(alias).get()

plugins {
  // Apply the common convention plugin for shared build configuration between library and application projects.
  id("com.example.demo.java-common-conventions")

  id("org.openapi.generator")
  id("org.springframework.boot")
}

dependencies {
  compileOnly(library("jackson-databind-nullable"))
  compileOnly(library("swagger-annotations"))
}

tasks.named<JavaCompile>("compileJava").configure { dependsOn(tasks.named("openApiGenerate")) }

openApiGenerate {
  generatorName.set("spring")
  inputSpec.set("${project.rootDir}/specs/openapi.yml")
  outputDir.set("${project.buildDir}/generated")
  configOptions.set(mapOf("delegatePattern" to "false", "interfaceOnly" to "true"))
}

sourceSets.main {
  java.srcDir("${openApiGenerate.outputDir.get()}/src/main/java")
}
