/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.example.demo.list;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

import org.junit.jupiter.api.Test;

class LinkedListTest {
  @Test
  void testConstructor() {
    var list = new LinkedList();
    assertThat(list.size(), is(0));
  }

  @Test
  void testAdd() {
    var list = new LinkedList();

    list.add("one");
    assertThat(list.size(), is(1));
    assertThat(list.get(0), is("one"));

    list.add("two");
    assertThat(list.size(), is(2));
    assertThat(list.get(1), is("two"));
  }

  @Test
  void testRemove() {
    var list = new LinkedList();

    list.add("one");
    list.add("two");
    assertThat(list.remove("one"), is(true));

    assertThat(list.size(), is(1));
    assertThat(list.get(0), is("two"));

    assertThat(list.remove("two"), is(true));
    assertThat(list.size(), is(0));
  }

  @Test
  public void testRemoveMissing() {
    var list = new LinkedList();

    list.add("one");
    list.add("two");
    assertThat(list.remove("three"), is(false));
    assertThat(list.size(), is(2));
  }
}
