/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CompletedImport } from './routes/completed'
import { Route as ActiveImport } from './routes/active'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CompletedRoute = CompletedImport.update({
  path: '/completed',
  getParentRoute: () => rootRoute,
} as any)

const ActiveRoute = ActiveImport.update({
  path: '/active',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/active': {
      preLoaderRoute: typeof ActiveImport
      parentRoute: typeof rootRoute
    }
    '/completed': {
      preLoaderRoute: typeof CompletedImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ActiveRoute,
  CompletedRoute,
])

/* prettier-ignore-end */
