/*
 * This file was generated by the Gradle 'init' task.
 */

plugins { id("com.example.demo.java-library-conventions") }

dependencies {
  api(project(":domain"))
  runtimeOnly("mysql:mysql-connector-java")
}
