/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
  `kotlin-dsl`
}

repositories {
  // Use the plugin portal to apply community plugins in convention plugins.
  gradlePluginPortal()
}

dependencies {
  implementation("com.diffplug.spotless:spotless-plugin-gradle:6.3.0")
  implementation("com.github.spotbugs.snom:spotbugs-gradle-plugin:5.0.6")
  implementation("io.spring.gradle:dependency-management-plugin:1.0.11.RELEASE")
  implementation("net.ltgt.gradle:gradle-errorprone-plugin:2.0.2")
  implementation("org.springframework.boot:spring-boot-gradle-plugin:2.6.4")
}
