name: reviewdog
on:
  pull_request:
    branches: [main]
permissions:
  contents: read
  pull-requests: write
jobs:
  eslint:
    name: ESlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - uses: reviewdog/action-eslint@v1
        with:
          fail_on_error: true
          level: error
          reporter: github-pr-review
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - run: npx --no -- prettier --write .
      - uses: reviewdog/action-suggester@v1
        with:
          fail_on_error: true
          level: error
          tool_name: Prettier
  spotless:
    name: Spotless
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew spotlessApply
      - uses: reviewdog/action-suggester@v1
        with:
          fail_on_error: true
          level: error
          tool_name: Spotless
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-yamllint@v1
        with:
          fail_on_error: true
          level: error
          reporter: github-pr-review
