/*
 * This file was generated by the Gradle 'init' task.
 */

plugins { id("com.example.demo.java-application-conventions") }

dependencies {
  implementation("org.springframework.boot:spring-boot-starter-validation")
  implementation("org.springframework.boot:spring-boot-starter-web")
  implementation(project(":application"))
  developmentOnly("org.springframework.boot:spring-boot-devtools")
  annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")
}

tasks.register<Copy>("processFrontendResources") {
  group = "Frontend"
  description = "Process frontend resources"
  dependsOn(project(":frontend").tasks.named("assembleFrontend"))
  from(project(":frontend").layout.projectDirectory.dir("dist"))
  into(layout.buildDirectory.dir("resources/main/static"))
}

tasks.named<ProcessResources>("processResources").configure {
  dependsOn(tasks.named("processFrontendResources"))
}
